mas "com.kirsteins.chords-and-scales-mac", id: 1435473426
mas "Craft", id: 1487937127
mas "DevUtils", id: 1533756032
mas "FileBot", id: 905384638
mas "Final Cut Pro", id: 424389933
mas "GoPro Player", id: 1460836908
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Logic Pro", id: 634148309
mas "Mactracker", id: 430255202
mas "Magnet", id: 441258766
mas "Metadatics", id: 554883654
mas "MIDI Loupe", id: 507075182
mas "MindNode", id: 1289197285
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PCalc", id: 403504866
mas "PDF Expert", id: 1055273043
mas "Playgrounds", id: 1496833156
mas "Remote Desktop", id: 409907375
mas "Speedtest", id: 1153157709
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "TNEF's Enough", id: 986621173
mas "Trello", id: 1278508951
mas "WhatsApp", id: 1147396723
mas "WiFi Explorer", id: 494803304
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650
mas "ZOA", id: 1581881354tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "neovim/neovim"
brew "agg"
brew "xz"
brew "autoconf"
brew "automake"
brew "awk"
brew "bash"
brew "bench"
brew "lzo"
brew "cmake"
brew "coreutils"
brew "curl"
brew "diffutils"
brew "docbook"
brew "docbook-xsl"
brew "dos2unix"
brew "duf"
brew "gcc"
brew "nettle"
brew "icu4c"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fop"
brew "fwup"
brew "fzf"
brew "gd"
brew "gdbm"
brew "git"
brew "git-flow"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "readline"
brew "librsvg"
brew "libtool"
brew "graphviz"
brew "grep"
brew "shared-mime-info"
brew "jq"
brew "lazygit"
brew "lego"
brew "less"
brew "libdvdcss"
brew "libepoxy"
brew "libffi"
brew "libusb-compat"
brew "libxml2"
brew "libxslt"
brew "libyaml"
brew "mas"
brew "midnight-commander"
brew "mosh"
brew "nano"
brew "neofetch"
brew "nmap"
brew "pandoc"
brew "paperkey"
brew "pgformatter"
brew "pkg-config"
brew "poppler"
brew "popt"
brew "portmidi"
brew "postgresql@15", restart_service: true, link: true
brew "pth"
brew "pwgen"
brew "qrencode"
brew "recode"
brew "rename"
brew "shellcheck"
brew "sqlite"
brew "squashfs"
brew "ssh-copy-id"
brew "tcl-tk"
brew "tidy-html5"
brew "tmux"
brew "tree"
brew "unixodbc"
brew "unzip"
brew "watch"
brew "wget"
brew "wxwidgets"
brew "xmlto"
brew "xxhash"
brew "zbar"
brew "zlib"
cask "basictex"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "keycastr"
cask "kitty"

